# JOB LEVEL TEMPLATE:
# Used to build XPlatCppSdk
# Reusable
# Meant to be run from the single CppTemplate pipeline (default), or
#   from a multi-pipeline such as publishing (should specify alternate params)

parameters:
- name: ApiSpecSource
  displayName: ApiSpecSource
  type: string
  default: -apiSpecGitUrl https://raw.githubusercontent.com/PlayFab/API_Specs/master/
- name: CommitMessage
  displayName: CommitMessage
  type: string
  default: Automated build from ADO Pipeline
- name: GitDestBranch
  displayName: GitDestBranch
  type: string
  default: doNotCommit
- name: GitJSetupBranch
  displayName: GitJSetupBranch
  type: string
  default: master
- name: GitSdkGenBranch
  displayName: GitSdkGenBranch
  type: string
  default: master
- name: SdkGenPrvTmplRepo
  displayName: SdkGenPrvTmplRepo
  type: string
  default: master
- name: isVersioned
  displayName: isVersioned
  type: boolean
  default: false
- name: BuildWindows
  displayName: BuildWindows
  type: boolean
  default: true
- name: TestWindows
  displayName: TestWindows
  type: boolean
  default: true
- name: SelfTemplateResource
  displayName: SelfTemplateResource
  type: string
  default: self

jobs:
- job: CppJobTemplate
  steps:
  - bash: echo CppJobTemplate
- job: CppTemplate
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: CppStepTemplate.yml
    parameters:
      ApiSpecSource: ${{ parameters.ApiSpecSource }}
      CommitMessage: ${{ parameters.CommitMessage }}
      GitDestBranch: ${{ parameters.GitDestBranch }}
      GitJSetupBranch: ${{ parameters.GitJSetupBranch }}
      GitSdkGenBranch: ${{ parameters.GitSdkGenBranch }}
      SdkGenPrvTmplRepo: ${{ parameters.SdkGenPrvTmplRepo }}
      isVersioned: ${{ parameters.isVersioned }}
      BuildWindows: ${{ parameters.BuildWindows }}
      TestWindows: ${{ parameters.TestWindows }}
      SelfTemplateResource: ${{ parameters.SelfTemplateResource }}
